  
# # 服务器前置任务(ubuntu使用)
- name: Pre_tasks of neo4j
  hosts: neo4j
  become: yes
  become_method: sudo
  gather_facts: False
  pre_tasks:
    - name: Install Python
      raw: sudo apt-get -y install python


# # 核心任务

- name: neo4j
  hosts: neo4j
  become: yes
  become_method: sudo

  roles:
    - { role: common, tags: "common"}  
    - { role: nginx, tags: "nginx"}
    - { role: neo4j, tags: "neo4j"}
    - { role: end, tags: "end"}