# 核心任务

- name: neo4j
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_Cloud, tags: "role_Cloud"} 
    - { role: role_nginx, tags: "role_nginx"}
    - { role: neo4j, tags: "neo4j"}
    - { role: role_preend, tags: "role_preend"}
    - { role: role_end, tags: "role_end" }