- name: Add neo4j repository key
  apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key

- name: Add neo4j repository
  apt_repository:
    repo: deb https://debian.neo4j.org/repo stable latest/

- name: Install neo4j
  apt:
    name: neo4j
    state: latest
    update_cache: yes
