- name: Add java8 repo
  apt_repository:
    repo: 'ppa:openjdk-r/ppa'

- name: Add neo4j repository key
  apt_key:
    url: https://debian.neo4j.org/neotechnology.gpg.key

- name: Add neo4j repository
  apt_repository:
    repo: deb https://debian.neo4j.org/repo stable/

- name: Install neo4j
  apt:
    name: neo4j
    update_cache: yes

- name: set reverse porxy
  copy: 
    src: default
    dest: /etc/nginx/conf.d/default.conf

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

  